spring:
  flyway:
      url: jdbc:postgresql://${DB_HOST_APP}:${DB_PORT_APP}/${DATA_BASE}
      user: ${DB_USER_APP:postgres}
      password: ${DB_PASSWORD_APP:postgres}
      locations: classpath:db/migration
      baselineOnMigrate: true
      validateOnMigrate: true
      clean-disabled: false
      clean-on-validation-error: true
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    open-in-view: false