spring:
  datasource:
    jdbcUrl: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATA_BASE:spring_batch_dbpartitionerlocaljob}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    open-in-view: false
  flyway:
      url: jdbc:postgresql://${DB_HOST_APP:localhost}:${DB_PORT_APP:5432}/${DATA_BASE:migracao_dados2}
      user: ${DB_USER_APP:postgres}
      password: ${DB_PASSWORD_APP:postgres}
      locations: classpath:db/migration
      baselineOnMigrate: true
      validateOnMigrate: true
      clean-disabled: false
      clean-on-validation-error: true
      enabled: true
app:
  datasource:
    jdbcUrl: jdbc:postgresql://${DB_HOST_APP:localhost}:${DB_PORT_APP:5432}/${DATA_BASE:migracao_dados2}
    username: ${DB_USER_APP:postgres}
    password: ${DB_PASSWORD_APP:postgres}
    driver-class-name: org.postgresql.Driver

migracaodados:
    totalRegistros: ${TOTAL_REGISTROS_ARQUIVO:20000}
    gridSize: 10