version: '3'
services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_MIN_MEMORY=512M   # Memória mínima para o ActiveMQ
      - ACTIVEMQ_MAX_MEMORY=1024M  # Memória máxima para o ActiveMQ
    volumes:
      - activemq-data:/data
      - activemq-logs:/var/log/activemq

volumes:
  activemq-data:
  activemq-logs: